#ifndef HIGHS4J_C_API
#define HIGHS4J_C_API

#include "highs_c_api.h"

#define K_HIGHS_MAXIMUM_STRING_LENGTH kHighsMaximumStringLength

#define K_HIGHS_STATUS_ERROR kHighsStatusError
#define K_HIGHS_STATUS_OK kHighsStatusOk
#define K_HIGHS_STATUS_WARNING kHighsStatusWarning

#define K_HIGHS_VAR_TYPE_CONTINUOUS kHighsVarTypeContinuous
#define K_HIGHS_VAR_TYPE_INTEGER kHighsVarTypeInteger
#define K_HIGHS_VAR_TYPE_SEMI_CONTINUOUS kHighsVarTypeSemiContinuous
#define K_HIGHS_VAR_TYPE_SEMI_INTEGER kHighsVarTypeSemiInteger
#define K_HIGHS_VAR_TYPE_IMPLICIT_INTEGER kHighsVarTypeImplicitInteger

#define K_HIGHS_OPTION_TYPE_BOOL kHighsOptionTypeBool
#define K_HIGHS_OPTION_TYPE_INT kHighsOptionTypeInt
#define K_HIGHS_OPTION_TYPE_DOUBLE kHighsOptionTypeDouble
#define K_HIGHS_OPTION_TYPE_STRING kHighsOptionTypeString

#define K_HIGHS_info_TYPE_INT64 kHighsInfoTypeInt64
#define K_HIGHS_info_TYPE_INT kHighsInfoTypeInt
#define K_HIGHS_info_TYPE_DOUBLE kHighsInfoTypeDouble

#define K_HIGHS_OBJSENSE_MINIMIZE kHighsObjSenseMinimize
#define K_HIGHS_OBJSENSE_MAXIMIZE kHighsObjSenseMaximize

#define K_HIGHS_MATRIX_FORMAT_COLWISE kHighsMatrixFormatColwise
#define K_HIGHS_MATRIX_FORMAT_ROWWISE kHighsMatrixFormatRowwise

#define K_HIGHS_HESSIAN_FORMAT_TRIANGULAR kHighsHessianFormatTriangular
#define K_HIGHS_HESSIAN_FORMAT_SQUARE kHighsHessianFormatSquare

#define K_HIGHS_SOLUTION_STATUS_NONE kHighsSolutionStatusNone
#define K_HIGHS_SOLUTION_STATUS_INFEASIBLE kHighsSolutionStatusInfeasible
#define K_HIGHS_SOLUTION_STATUS_FEASIBLE kHighsSolutionStatusFeasible

#define K_HIGHS_BASIS_VALIDITY_INVALID kHighsBasisValidityInvalid
#define K_HIGHS_BASIS_VALIDITY_VALID kHighsBasisValidityValid

#define K_HIGHS_PRESOLVE_STATUS_NOT_PRESOLVED kHighsPresolveStatusNotPresolved
#define K_HIGHS_PRESOLVE_STATUS_NOT_REDUCED kHighsPresolveStatusNotReduced
#define K_HIGHS_PRESOLVE_STATUS_INFEASIBLE kHighsPresolveStatusInfeasible
#define K_HIGHS_PRESOLVE_STATUS_UNBOUNDED_OR_INFEASIBLE kHighsPresolveStatusUnboundedOrInfeasible
#define K_HIGHS_PRESOLVE_STATUS_REDUCED kHighsPresolveStatusReduced
#define K_HIGHS_PRESOLVE_STATUS_REDUCED_TO_EMPTY kHighsPresolveStatusReducedToEmpty
#define K_HIGHS_PRESOLVE_STATUS_TIMEOUT kHighsPresolveStatusTimeout
#define K_HIGHS_PRESOLVE_STATUS_NULL_ERROR kHighsPresolveStatusNullError
#define K_HIGHS_PRESOLVE_STATUS_OPTIONS_ERROR kHighsPresolveStatusOptionsError
#define K_HIGHS_PRESOLVE_STATUS_OUT_OF_MEMORY kHighsPresolveStatusOutOfMemory

#define K_HIGHS_MODEL_STATUS_NOTSET kHighsModelStatusNotset
#define K_HIGHS_MODEL_STATUS_LOAD_ERROR kHighsModelStatusLoadError
#define K_HIGHS_MODEL_STATUS_MODEL_ERROR kHighsModelStatusModelError
#define K_HIGHS_MODEL_STATUS_PRESOLVE_ERROR kHighsModelStatusPresolveError
#define K_HIGHS_MODEL_STATUS_SOLVE_ERROR kHighsModelStatusSolveError
#define K_HIGHS_MODEL_STATUS_POSTSOLVE_ERROR kHighsModelStatusPostsolveError
#define K_HIGHS_MODEL_STATUS_MODEL_EMPTY kHighsModelStatusModelEmpty
#define K_HIGHS_MODEL_STATUS_OPTIMAL kHighsModelStatusOptimal
#define K_HIGHS_MODEL_STATUS_INFEASIBLE kHighsModelStatusInfeasible
#define K_HIGHS_MODEL_STATUS_UNBOUNDED_OR_INFEASIBLE kHighsModelStatusUnboundedOrInfeasible
#define K_HIGHS_MODEL_STATUS_UNBOUNDED kHighsModelStatusUnbounded
#define K_HIGHS_MODEL_STATUS_OBJECTIVE_BOUND kHighsModelStatusObjectiveBound
#define K_HIGHS_MODEL_STATUS_OBJECTIVE_TARGET kHighsModelStatusObjectiveTarget
#define K_HIGHS_MODEL_STATUS_TIME_LIMIT kHighsModelStatusTimeLimit
#define K_HIGHS_MODEL_STATUS_ITERATION_LIMIT kHighsModelStatusIterationLimit
#define K_HIGHS_MODEL_STATUS_UNKNOWN kHighsModelStatusUnknown
#define K_HIGHS_MODEL_STATUS_SOLUTION_LIMIT kHighsModelStatusSolutionLimit
#define K_HIGHS_MODEL_STATUS_INTERRUPT kHighsModelStatusInterrupt
#define K_HIGHS_MODEL_STATUS_MEMORY_LIMIT kHighsModelStatusMemoryLimit

#define K_HIGHS_BASIS_STATUS_LOWER kHighsBasisStatusLower
#define K_HIGHS_BASIS_STATUS_BASIC kHighsBasisStatusBasic
#define K_HIGHS_BASIS_STATUS_UPPER kHighsBasisStatusUpper
#define K_HIGHS_BASIS_STATUS_ZERO kHighsBasisStatusZero
#define K_HIGHS_BASIS_STATUS_NONBASIC kHighsBasisStatusNonbasic

#endif
